/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author lisan
 */
public class VistaAddPersona extends javax.swing.JFrame {

    /**
     * Creates new form VistaAddPersona
     */
    public VistaAddPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddPer = new javax.swing.JLabel();
        inpNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblMail1 = new javax.swing.JLabel();
        inpMail1 = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        inpMail2 = new javax.swing.JTextField();
        lblTelefono2 = new javax.swing.JLabel();
        inpMail3 = new javax.swing.JTextField();
        btnCancelarPersona = new javax.swing.JButton();
        btnCancelarPersona1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGREGAR PERSONA");
        setBackground(new java.awt.Color(204, 255, 255));

        lblAddPer.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        lblAddPer.setForeground(new java.awt.Color(0, 0, 0));
        lblAddPer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddPer.setText("AGREGAR PERSONA");

        inpNombre.setToolTipText("Escriba el NOMBRE de la persona a añadir");
        inpNombre.setName("inpNombre"); // NOI18N

        lblNombre.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("NOMBRE");
        lblNombre.setToolTipText("");
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre.setName(""); // NOI18N

        lblMail1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblMail1.setForeground(new java.awt.Color(0, 0, 0));
        lblMail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMail1.setText("MAIL");
        lblMail1.setToolTipText("");
        lblMail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMail1.setName(""); // NOI18N

        inpMail1.setToolTipText("Escriba el MAIL de la persona a añadir");
        inpMail1.setName("inpNombre"); // NOI18N

        lblTelefono1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefono1.setText("TELEFONO");
        lblTelefono1.setToolTipText("");
        lblTelefono1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTelefono1.setName(""); // NOI18N

        inpMail2.setToolTipText("Escriba el TELEFONO de la persona a añadir");
        inpMail2.setName("inpNombre"); // NOI18N

        lblTelefono2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblTelefono2.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefono2.setText("D.N.I");
        lblTelefono2.setToolTipText("");
        lblTelefono2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTelefono2.setName(""); // NOI18N

        inpMail3.setToolTipText("Escriba el TELEFONO de la persona a añadir");
        inpMail3.setName("inpNombre"); // NOI18N

        btnCancelarPersona.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        btnCancelarPersona.setText("CANCELAR");

        btnCancelarPersona1.setFont(new java.awt.Font("Lucida Console", 1, 34)); // NOI18N
        btnCancelarPersona1.setText("AÑADIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpMail1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpMail2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpMail3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(btnCancelarPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpMail3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarPersona1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        inpNombre.getAccessibleContext().setAccessibleName("Nombre");
        inpMail3.getAccessibleContext().setAccessibleDescription("Escriba el DNI de la persona a añadir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAddPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAddPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAddPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAddPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAddPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPersona;
    private javax.swing.JButton btnCancelarPersona1;
    private javax.swing.JTextField inpMail1;
    private javax.swing.JTextField inpMail2;
    private javax.swing.JTextField inpMail3;
    private javax.swing.JTextField inpNombre;
    private javax.swing.JLabel lblAddPer;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    // End of variables declaration//GEN-END:variables
}
