/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author lisan
 */
public class VistaAddHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaAddPersona
     */
    public VistaAddHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddPer = new javax.swing.JLabel();
        inpNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        inpTipo = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        inpCapacidad = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        inpEstado = new javax.swing.JTextField();
        btnCancelarPersona = new javax.swing.JButton();
        btnCancelarPersona1 = new javax.swing.JButton();
        inpPrecioBase = new javax.swing.JTextField();
        lblPrecioBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGREGAR PERSONA");
        setBackground(new java.awt.Color(204, 255, 255));

        lblAddPer.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        lblAddPer.setForeground(new java.awt.Color(0, 0, 0));
        lblAddPer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddPer.setText("AGREGAR HABITACION");

        inpNumero.setToolTipText("Escriba el NOMBRE de la persona a añadir");
        inpNumero.setName("inpNumero"); // NOI18N

        lblNumero.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("NÚMERO");
        lblNumero.setToolTipText("");
        lblNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNumero.setName(""); // NOI18N

        lblTipo.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("TIPO");
        lblTipo.setToolTipText("");
        lblTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTipo.setName(""); // NOI18N

        inpTipo.setToolTipText("Escriba el MAIL de la persona a añadir");
        inpTipo.setName("inpNombre"); // NOI18N

        lblCapacidad.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        lblCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapacidad.setText("CAPACIDAD");
        lblCapacidad.setToolTipText("");
        lblCapacidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCapacidad.setName(""); // NOI18N

        inpCapacidad.setToolTipText("Escriba el TELEFONO de la persona a añadir");
        inpCapacidad.setName("inpNombre"); // NOI18N
        inpCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCapacidadActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("ESTADO");
        lblEstado.setToolTipText("");
        lblEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEstado.setName(""); // NOI18N

        inpEstado.setToolTipText("Escriba el TELEFONO de la persona a añadir");
        inpEstado.setName("inpNombre"); // NOI18N

        btnCancelarPersona.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        btnCancelarPersona.setText("CANCELAR");

        btnCancelarPersona1.setFont(new java.awt.Font("Lucida Console", 1, 34)); // NOI18N
        btnCancelarPersona1.setText("AÑADIR");

        inpPrecioBase.setToolTipText("Escriba el TELEFONO de la persona a añadir");
        inpPrecioBase.setName("inpNombre"); // NOI18N
        inpPrecioBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPrecioBaseActionPerformed(evt);
            }
        });

        lblPrecioBase.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        lblPrecioBase.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioBase.setText("PRECIO BASE");
        lblPrecioBase.setToolTipText("");
        lblPrecioBase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPrecioBase.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelarPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnCancelarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecioBase)
                                        .addGap(13, 13, 13))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inpEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(inpPrecioBase)
                            .addComponent(inpCapacidad)
                            .addComponent(inpTipo)
                            .addComponent(inpNumero))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inpPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        inpNumero.getAccessibleContext().setAccessibleName("Nombre");
        inpEstado.getAccessibleContext().setAccessibleDescription("Escriba el DNI de la persona a añadir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCapacidadActionPerformed

    private void inpPrecioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPrecioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpPrecioBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAddHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAddHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAddHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAddHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAddHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPersona;
    private javax.swing.JButton btnCancelarPersona1;
    private javax.swing.JTextField inpCapacidad;
    private javax.swing.JTextField inpEstado;
    private javax.swing.JTextField inpNumero;
    private javax.swing.JTextField inpPrecioBase;
    private javax.swing.JTextField inpTipo;
    private javax.swing.JLabel lblAddPer;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecioBase;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
